"""DOCUMENTATION_WRITER.py - Automatic documentation generator for applications."""

from datetime import datetime
from dataclasses import dataclass

@dataclass
class Documentation:
    readme: str; api_docs: str; deployment_guide: str; user_guide: str; changelog: str

class DocumentationWriter:
    """Generates README, API docs, deployment guides, user guides."""
    def __init__(self): self.generation_count = 0

    def generate_readme(self, spec: dict) -> str:
        n, d = spec.get("name", "app"), spec.get("description", "An application")
        f_md = "\n".join(f"- {f.replace('_', ' ').title()}" for f in spec.get("features", []))
        t_md = "\n".join(f"- **{k}**: {v}" for k, v in spec.get("tech_stack", {}).items())
        return f'''# {n.replace("_", " ").title()}\n\n{d}\n\n## Features\n\n{f_md}\n\n## Tech Stack\n\n{t_md}\n\n## Quick Start\n\n### Prerequisites\n- Python 3.8+\n- Node.js 16+\n- pip\n\n### Installation\n```bash\ngit clone https://github.com/your-username/{n}.git\ncd {n}\npip install -r requirements.txt\npython app.py\n```\n\nOpen http://localhost:5000\n\n## API Documentation\nSee [API_DOCS.md](./docs/API_DOCS.md)\n\n## Deployment\nSee [DEPLOYMENT.md](./docs/DEPLOYMENT.md)\n\n## Contributing\n1. Fork → 2. Branch → 3. Commit → 4. Push → 5. PR\n\n## License\nMIT License\n\n---\nGenerated by AI App Generator\n'''

    def generate_api_docs(self, spec: dict) -> str:
        n, features = spec.get("name", "app"), spec.get("features", [])
        eps = ['### Health Check\n`GET /health` → `{"status": "healthy"}`\n']
        if "user_authentication" in features:
            eps.append('### Auth\n`POST /api/auth/login` - Login with email/password → JWT token\n`POST /api/auth/register` - Create account\n')
        if "database" in features:
            eps.append('### Data\n`GET /api/data` - List items\n`POST /api/data` - Create item\n')
        return f'''# API - {n.replace("_", " ").title()}\n\n## Base URL\n`http://localhost:5000`\n\n## Auth\n`Authorization: Bearer <token>`\n\n## Endpoints\n{"".join(eps)}\n## Errors\n`{{"error": "msg", "code": N}}` | 400=BadRequest, 401=Unauth, 404=NotFound, 500=Error\n\n---\nGenerated by AI App Generator\n'''

    def generate_deployment_guide(self, spec: dict) -> str:
        n = spec.get("name", "app")
        return f'''# Deploy - {n.replace("_", " ").title()}\n\n## Railway\n```bash\nnpm i -g @railway/cli && railway login && railway init --name {n} && railway up && railway domain\n```\n\n## Netlify\n```bash\nnpm run build && netlify deploy --prod\n```\n\n## Docker\n```bash\ndocker build -t {n} . && docker run -p 5000:5000 {n}\n```\n\n## Env Vars\n| Var | Required |\n|-----|----------|\n| FLASK_ENV | Yes |\n| DATABASE_URL | Yes |\n| JWT_SECRET | Yes |\n| PORT | No |\n\n## Monitor\nHealth: `/health` every 30s, alert on 3 failures\n\n---\nGenerated by AI App Generator\n'''

    def generate_user_guide(self, spec: dict) -> str:
        n, features = spec.get("name", "app"), spec.get("features", [])
        secs = []
        if "user_authentication" in features: secs.append('## Account\n- Register: Click Register → Enter email/password → Create Account\n- Login: Click Login → Enter credentials → Sign In\n')
        if "database" in features: secs.append('## Data\n- Create: Dashboard → Add New → Fill fields → Save\n- Edit: Click item → Modify → Update\n- Delete: Select → Delete → Confirm\n')
        return f'''# User Guide - {n.replace("_", " ").title()}\n\nWelcome! This guide helps you get started.\n\n{"".join(secs)}\n## Troubleshooting\n- Can't login? Check credentials, reset password, clear cache\n- Data not loading? Refresh, check connection, contact support\n\n## Help\nEmail: support@{n.replace("_", "")}.com | Docs: /docs | FAQ: /faq\n\n---\nGenerated by AI App Generator\n'''

    def generate_changelog(self, spec: dict) -> str:
        n, today = spec.get("name", "app"), datetime.now().strftime("%Y-%m-%d")
        return f'''# Changelog - {n.replace("_", " ").title()}\n\n## [1.0.0] - {today}\n\n### Added\n- Initial release, core structure, auth, database, API, tests, deploy configs\n\n### Security\n- Input validation, XSS/CSRF protection, JWT auth\n\n---\nGenerated by AI App Generator\n'''

    def generate_all(self, spec: dict) -> Documentation:
        """Generate all documentation."""
        self.generation_count += 1
        return Documentation(self.generate_readme(spec), self.generate_api_docs(spec), self.generate_deployment_guide(spec), self.generate_user_guide(spec), self.generate_changelog(spec))

    def to_dict(self, docs: Documentation) -> dict:
        counts = [docs.readme.count("\n"), docs.api_docs.count("\n"), docs.deployment_guide.count("\n"), docs.user_guide.count("\n"), docs.changelog.count("\n")]
        return {"readme_lines": counts[0], "api_docs_lines": counts[1], "deployment_lines": counts[2], "user_guide_lines": counts[3], "changelog_lines": counts[4], "total_lines": sum(counts)}

if __name__ == "__main__":
    print("=" * 60 + "\nDOCUMENTATION WRITER TEST\n" + "=" * 60)
    spec = {"name": "test_app", "description": "Test app", "features": ["user_authentication", "database", "rest_api"], "tech_stack": {"frontend": "React", "backend": "Flask", "database": "SQLite"}}
    docs = DocumentationWriter().generate_all(spec)
    s = DocumentationWriter().to_dict(docs)
    print(f"\nREADME: {s['readme_lines']} | API: {s['api_docs_lines']} | Deploy: {s['deployment_lines']} | User: {s['user_guide_lines']} | Changelog: {s['changelog_lines']} | Total: {s['total_lines']}")
    print("=" * 60 + "\nOPERATIONAL\n" + "=" * 60)
